### ISSUE TITLE
itermax governs total number of iteration instead of stopping criteria?

### ISSUE THREAD

**Issue by ecosang** [eddelbuettel/rcppde#16]
Hello,  it looks like
`itermax` governs total number of iteration instead of stopping criteria. 
WIthout any `itermax` value, the optimizer runs 200. If I have specific number in `itermax`, then the optimizer runs exactly by that number specified in `itermax`.

Here is my device info.

R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RcppDE_0.1.5         RevoUtils_10.0.7     RevoUtilsMath_10.0.1

loaded via a namespace (and not attached):
[1] compiler_3.4.3 tools_3.4.3    yaml_2.1.16    Rcpp_0.12.14

**Comment by eddelbuettel** [comment]
That strikes as "behaves as documented".  Please see `help(DEoptim.control)` which has

```
    \item{itermax}{the maximum iteration (population generation) allowed.
      Default is \code{200}.}
```

Note that there are also other stopping criteria.

**Comment by ecosang** [comment]
Thanks. I think it is the problem of `DEoptim` library, not `RcppDE`.
I mean the algorithm runs as many as `itermax` regardless of the other criteria.
Foe example, if I put `itermax=10000` , it runs 10000 times even if it is converged. 
Thanks
