### ISSUE TITLE
vignettes/RcppDE.Rnw

### ISSUE THREAD

**Issue by sildeag** [eddelbuettel/rcppde#9]
If you have problems with Compile PDF in RStudio 1.0.44 (R 3.3.2), I found that changing line 65 from "%% need no \usepackage{Sweave.sty}" to "\usepackage{Sweave}" eliminated error.

**Comment by eddelbuettel** [comment]
Thanks for the report but note that
- it's a standard meta-comment we always needed (and I forget the details) so I am not going to remove it
- this is a Sweave not knitr vignette so you may have to adjust your processing options
- I just checked and it builds 'as is' for me, so this really looks like a local issue.
- what _really_ matters is what `R CMD check` says, and so far that always passed
